spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/SSM_Project?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/SSM_Project?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml

server:
  tomcat:
    uri-encoding: UTF-8
